### ISSUE TITLE
On naming conventions

### ISSUE THREAD

**Issue by yumaikas** [janet-lang/pkgs#29]
Overall, I believe that the current naming conventions in CONTRINBUTING.md are overly restrictive. We have a wide variety of naming schemes extant in use in Janet, and I believe the flexibility of naming schemes is a benefit of Janet, and that being overly presecriptive keeps people from adding useful work to pkgs. It's certainly added hassle and fuss to my attempts to do so in the past, when I suggested testament.

Not that I believe that we should have *no* naming conventions, but right now this feels like too much process for what is a very small community at the moment.

**Comment by goto-engineering** [comment]
Several people have expressed that they're currently not publishing to `pkgs` because they find it a bit restrictive. Therefore I support making it easier. Anything that's not outright malicious/clearly broken should be ok, I think.

**Comment by andrewchambers** [comment]
I don't know if I would say too restrictive, but even making a PR to the pkgs repo is another step. I might also just be lazy at times.

**Comment by sogaiu** [comment]
Perhaps people wouldn't mind spelling out details about naming that are problematic?  As it stands, I'm just imagining things with no specifics.

If I'm misremembering the following, please feel to correct.  I think one of the factors that contributed to the current content of CONTRIBUTING.md was this: https://github.com/janet-lang/janet/discussions/563#discussioncomment-275132

**Comment by ahungry** [comment]
I often use packages with names that fall into the disagreeable ones - does anyone have a *technical* reason this is ill-advised, versus a subjective/bike-shedding/just your opinion man, reason?

```

    Good package names:
        my-package
        thing
        thing@bakpakin (for a fork of the package)
    Bad package names:
        mypackage
        my_package
        MyPackage
        my package
        my.package.git
        org.this.is.not.java.AbstractWidgetFactoryProducer
```

Why would something like "po-box" be better than "pobox" (one example).

Why is a completely nonsensical name like "<name of some Good Place character>" better than "com.ahungry.crypt.jwt"? 

Why is "testament" better than "Testament"?

I don't believe anything in janet forbids package names having single words, capitals, underscores, or java-esque (descriptive) names.

Can someone explain it to me in a way that avoids the reasons amounting to the opinion of one or a few?

**Comment by uvtc** [comment]
I prefer the more restrictive naming.

  * it's more ergonomic: I can glance at the name of a thing and quickly recognize what it probably is. For example, I glance at a directory and if it contains a project.janet I know it's probably a Janet project. Maybe this is subjective, but it saves some human cpu cycles for me.
  * easier to search for. That is, instead of searching for "my_package", then "MyPackage", then "my.package", "my package", etc. I already know what my search term will be something like "my-package". Arguably may save some time / frustration.
  * Consistent naming may also help tooling down the road.

That said, I'm sure that @bakpakin has made many decisions about how Janet will work that are considered subjective. I think that some style-related decisions by the bdfl early-on can avoid issues further down the road.

**Comment by uvtc** [comment]
@ahungry , there doesn't seem to be anything wrong with "com.ahungry.my-package". That not only "namespaces" the package, but uses the suggested kebab-case for the package name, no?

The "`my-package@ahungry`" convention I'm seeing (on a few packages in `pkgs`) with the "at" sign in there seems weird to me. It conveys almost as much info as "`com.ahungry.my-package`" ( <-- I prefer this style myself).

Of more importance to me is consistency between the project.janet's `:name` value and the git repo's name.

**Comment by bakpakin** [comment]
Consistency in naming is good because it makes it easier to find things. Also, there is no reason not to be consistent. People who want to use their own naming scheme at missing the point - it doesn't matter what the convention is, as long as we have one. And we may as well use the existing conventions for Janet bindings (with allowances for conveying other information that is important).

And I think we all know this is a bit of bike-shedding :)

**Comment by ahungry** [comment]
So, renaming from com.ahungry.crypt.jwt to "jama" would follow the standard more closely - would you get more info about the library from a randomly selected character name from The Good Place?

To me, that seems doubtful...

If everyone else is jumping off a bridge, would you?  

If the standard doesn't make sense (the final line of "this.is.not.java" is clearly a jab at one particular naming convention some author(s) dislike) I think it makes sense to diverge from it, however if that causes exclusion from this repo, it comes full circle into identifying why some may not care to jump through hoops to be part of it.

**Comment by pepe** [comment]
I am late here as I'm on the vacation. 

We had this discussion before when I was compiling contribution guidelines and lot of the arguments were already given, yet when I asked for some actual recommendations none was given.

I think answer by @bakpakin is closest to what I feel. 

And jump out of the window argument I find very weak.

**Comment by bakpakin** [comment]
I'm putting down my foot and leaving the naming conventions as is. If someone wants to propose different naming conventions, or use different conventions in their own package listing, feel free to do so. But I see no reason to complain about a naming convention - it is incredibly easy to enforce and generally helpful for finding things.
